### ISSUE TITLE
Any update for fifa 22 web app

### ISSUE THREAD

**Issue by ruubmarges** [oRastor/fut23-web-app#70]
Hi! I was wondering if there is going to be a autobuyer for fifa 22? Thank you in advance!

**Comment by Kongux** [comment]
Hey, does this mean no autobuyer for fifa 22? :(

**Comment by ruubmarges** [comment]
Idk.. Any update @oRastor ?

**Comment by oRastor** [comment]
I will try

**Comment by Kongux** [comment]
I would literally love you !!😂

**Comment by ruubmarges** [comment]
The autobuyer does work, only the menu for buying players doens't show. It doesnt sell it automatically. Packs can't be opened either. Maybe that is related.

**Comment by oRastor** [comment]
Yes, it works

**Comment by ruubmarges** [comment]
Is there Any update about opening the packs and/of automatically stelling players in the menu? Thank you for the buyerbtw!!

**Comment by oRastor** [comment]
> Is there Any update about opening the packs and/of automatically stelling players in the menu? Thank you for the buyerbtw!!

I am trying to understand what is the reason. But if you need to open packs, then for now it is better to restart applications without a script.

**Comment by ruubmarges** [comment]
Yes i did that already. But i Just wanted to inform you! Thanks.

**Comment by Redaa91** [comment]
Does the autobuyer work Orest ? Is it ''safe'' to use already ?
Ive send u an email also.

**Comment by oRastor** [comment]
Yes, I use it.

**Comment by lacktophan** [comment]
@oRastor First of all thanks for the auto buyer . It works great. Could you please make few changes so it would help to avoid EA ban. I was hoping if you can add a tab where we can have option to tell auto buyer to stop after 1 search fail. search fails when EA soft ban us usually and if bot continues to run that would lead to perm BAN.  Also few suggestion if you are able to do it. please add sell with futbin option that would save us coins cuz sometime we get good card and goes for cheap with futbin optin it will go for lot higher.

Thanks for all you do!

**Comment by Redaa91** [comment]
> @oRastor First of all thanks for the auto buyer . It works great. Could you please make few changes so it would help to avoid EA ban. I was hoping if you can add a tab where we can have option to tell auto buyer to stop after 1 search fail. search fails when EA soft ban us usually and if bot continues to run that would lead to perm BAN. Also few suggestion if you are able to do it. please add sell with futbin option that would save us coins cuz sometime we get good card and goes for cheap with futbin optin it will go for lot higher.
> 
> Thanks for all you do!

This is something I worry about for some years now because if it keeps running it does indeed lead to perm ban way faster

**Comment by douwe130989** [comment]
Nice option for trading. 
At my place the autobuyer doesn't sell the players when i bought them. 
When i bought players i isn't in the screen on the right. 
Is this going to update? Now i have much work with selling the players etc. ;)

**Comment by oRastor** [comment]
"Failed search" means that search request returns an unexpected answer? In 21 version I added functional that's handle special soft ban answer and stop search and start sound effect. It working in 22 version too. But After reload page I not receive puzzle... Something new... I'll keep watching.

**Comment by oRastor** [comment]
I want to add 4 new killing features. I saw that some people sell this script on Instagram. Someone copied it into another repository and claim donations.
So I decided to make a page on patreon, where people who support the project can vote for new features and get them first. If this gets a response, I will continue to refine the script. Thank you for understanding.

https://www.patreon.com/fut22_automatic

**Comment by ruubmarges** [comment]
Can you tell me what the new featured are about to be? If im interested i Will subscribe

**Comment by oRastor** [comment]
Features list are available on patreon page

**Comment by ruubmarges** [comment]
I cant find it. Its locked

**Comment by douwe130989** [comment]
Is it going to update that autobuyer sell the players and items when i bought them? 
That's all autobuyer is about in my opinion ;)

**Comment by oRastor** [comment]
> Is it going to update that autobuyer sell the players and items when i bought them?
> That's all autobuyer is about in my opinion ;)

It already works this way

**Comment by douwe130989** [comment]
> > Is it going to update that autobuyer sell the players and items when i bought them?
> > That's all autobuyer is about in my opinion ;)
> 
> It already works this way

Not at my place... The players and items are going to my main page, where i must store them to club or sell from there.. In the right screen at autobuyer doesn't come anything.. Autobuyer ready and then a white field.. 
In fifa 21 down there i can see when i bought a player ore not. Now it stays white and no notifications about buying etc.

**Comment by douwe130989** [comment]
![image](https://user-images.githubusercontent.com/91298971/134731455-bf81a1b6-9e72-4bf5-8079-bc18469734e4.png)

**Comment by ruubmarges** [comment]
This is also my problem

**Comment by oRastor** [comment]
Because you set up too big max buy now price! Bad screenshot. Give me a screenshot where we can find in search result items that satisfy autobuyer criteria for buy request!

**Comment by ruubmarges** [comment]
![image](https://user-images.githubusercontent.com/72319981/134733554-221b4469-a40a-4b8d-bdd4-5775b806ae34.png)
Here is the same idea. I have a low buy filter. It autobuys for me, but it doens't automatically sell. Instead it is send to sell/store hub. You have to set the sell price by yourself, just like normal selling.

**Comment by ruubmarges** [comment]
![image](https://user-images.githubusercontent.com/72319981/134733796-62732a71-68c2-4775-966c-36e1f3219e86.png)
This is the menu, no instant selling.

**Comment by oRastor** [comment]
https://github.com/oRastor/fut22-web-app/issues/71

it was fixed 2 days ago

**Comment by douwe130989** [comment]
That's what i am talking about.. This doesn't work at my autobuyer. 
Why can this happen by us 2? It isn't fixed i think...

**Comment by douwe130989** [comment]
![image](https://user-images.githubusercontent.com/91298971/134734495-4e1a552e-718d-4e8d-bb58-e5b9b34e5f38.png)

Here is one on the transferlist for 1400 and 2300.. I set him up for 2300 nothing happened in the right screen.. 

![image](https://user-images.githubusercontent.com/91298971/134734583-044865dd-5119-4ec9-9f6e-ef96d92d4d2d.png)
They went up here.. And i must sell him by my self..

**Comment by oRastor** [comment]
because you haven't installed the latest version

**Comment by ruubmarges** [comment]
Hmm! Maybe that is the case. Do you have a link to the latest version?

**Comment by douwe130989** [comment]
Where can we download the latest version?

**Comment by oRastor** [comment]
https://github.com/oRastor/fut22-web-app/raw/master/fut22-autobuyer.user.js

**Comment by ruubmarges** [comment]
You sir, are freaking amazing! Thank you so much! Have a nice weekend.

**Comment by douwe130989** [comment]
![image](https://user-images.githubusercontent.com/91298971/134736469-be7f9a30-d478-4a69-8949-f0f51de4c0b0.png)
It works, But the screen is a bit strange ;)

**Comment by oRastor** [comment]
<img width="949" alt="134736469-be7f9a30-d478-4a69-8949-f0f51de4c0b0 png (1920×1080) 🔊 2021-09-24 23-35-24" src="https://user-images.githubusercontent.com/1734394/134736692-87ba6ea9-63c3-40e1-b5be-10dcfd6e5725.png">
Because you enabled 3 different scripts

**Comment by douwe130989** [comment]
I see.. Thanks mate. It works well right now!! 
have a good weekend!

**Comment by Smeerboef** [comment]
Hello guys, what other 2 scripts do i need to let it work? I only have the master in tampermonkey rn.

**Comment by Smeerboef** [comment]
Or is there something else that doesn't work for me

**Comment by oRastor** [comment]
only one script is needed!

**Comment by Smeerboef** [comment]
It doesn't work for me? Any tips to help me?

**Comment by daku92** [comment]
Hi,
Have anyone a sniping filter?
Regards

**Comment by ABFIF** [comment]
I bought this on Ebay last year and was mad when I realized it was free. I will definitely be joining your patreon sometime this week. This was great for me last year can't wait to make more coins using it again this year.

**Comment by KhairulAzmi21** [comment]
do @oRastor open for patreon ?
