### ISSUE TITLE
Search does not refresh

### ISSUE THREAD

**Issue by SVG3635** [oRastor/fut23-web-app#96]
Hey!

I have been using your autobuyer since fifa 21, but this time it does not work "perfectly".
When you search without changing any variable (buy now or bid now) then you keep getting the same results.
I could not get anything. After i started changing this manually (changing the bid now minimum from 200 to 250 back and forth), i got a lot of new results and a lot of buys.
Maybe this can be implemented in the code? (I am not good at coding so i would not know if this is possible)

Kind regards
SVG

**Comment by oRastor** [comment]
fixed

**Comment by philx17** [comment]
i think it is not working and not fixed.... I have the same issue. 
And can only solve it with changing any min or max bid after each search request...

**Comment by oRastor** [comment]
Did you test the new version?

> i think it is not working and not fixed.... I have the same issue. And can only solve it with changing any min or max bid after each search request...

**Comment by philx17** [comment]
1.5.5

**Comment by oRastor** [comment]
Can you record a video? I use version 1.5.5 for two days without any problems

**Comment by philx17** [comment]
I hope you can see it in this record....
I think he cached the search. 
And only after update a parameter or after 3 -4 searchrequest he update the list 

https://user-images.githubusercontent.com/32899622/192729430-d7ef113d-b257-4954-bc7f-b328f706da8f.mp4

**Comment by philx17** [comment]
It looks like that sometimes the search is working and sometimes not directly. 
So you miss some ne cards

**Comment by SVG3635** [comment]
Yes, it is the same for me.

Op wo 28 sep. 2022 om 10:51 schreef philx17 ***@***.***>

**Comment by oRastor** [comment]
Client cache clearing every request. And for every request we generate a random max bid value to prevent server cache, but not showing it in form.

Sometimes server return already completed trades, but we mark them with "*" if we tried to purchase them and don't try to buy them.
![image](https://user-images.githubusercontent.com/1734394/192768271-4739f40b-a5db-48c7-9b1a-afd5a6d75102.png)

I will try to test changing any other criteria. 

But I think that servers add new items to search requests more often than clearing old ones. So you can often see when search responses consist of new items and already completed items. But with your logic, it must consist only of new items.

**Comment by craigpbrown** [comment]
I've also encountered the same issue as @SVG3635 and @philx17.

I have two accounts so have been able to run them side by side and there is a significant difference when I change the search criteria (normally the min bid/buy prices).

Could you implement some sort of IF/switch statement that would set the min bid/buy price ahead of each search? Something like this (but much more elegant):

if (currentIteration == 0) {
	minBid = 0;
    minBuy = 150;
    currentIteration = 1;
} else if (currentIteration == 1) {
	minBid = 0;
    minBuy = 200;
    currentIteration = 2;
} else if (currentIteration == 2) {
	minBid = 0;
    minBuy = 250;
    currentIteration = 3;
} else if (currentIteration == 3) {
	minBid = 0;
    minBuy = 300;
    currentIteration = 4;
} else if (currentIteration == 4) {
	minBid = 0;
    minBuy = 350;
    currentIteration = 5;
} else if (currentIteration == 5) {
	minBid = 150;
    minBuy = 200;
    currentIteration = 6;
} else if (currentIteration == 6) {
	minBid = 150;
    minBuy = 250;
    currentIteration = 7;
} else if (currentIteration == 7) {
	minBid = 150;
    minBuy = 300;
    currentIteration = 8;
} else if (currentIteration == 8) {
	minBid = 150;
    minBuy = 350;
    currentIteration = 0;
}

**Comment by oRastor** [comment]
implemented new logic with visualization on front

**Comment by craigpbrown** [comment]
> implemented new logic with visualization on front

Absolutely perfect mate - thanks very much
